@url=http://localhost:3001/api
@json=Content-Type:application/x-www-form-urlencoded
###//获取所有用户
get {{url}}/users

###//注册
post {{url}}/register
{{json}}

{
  "username":"usedr2y91",
  "password":"123456"
}
###//登录
post {{url}}/login
{{json}}

{
  "username":"user3",
  "password":"123456"
}
###//个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZmRkMzVhMGI0MDNiMDA0Yzc4NTg5MCIsInRpbWUiOjE1NzcwNjUxOTIzOTQsImlhdCI6MTU3NzA2NTE5Mn0.WHyKm72p6MlvUowSP1wM2y7qbxMHBCIW46hud1argUw